#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=$PATH:~/packages

# Tell ls to be colourful
export CLICOLOR=1
#export LSCOLORS=Exfxcxdxbxegedabagacad
#export LS_COLORS="no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:*.sh=01;32:*.csh=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.bz=01;31:*.tz=01;31:*.rpm=01;31:*.cpio=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.xbm=01;35:*.xpm=01;35:*.png=01;35:*.tif=01;35:"

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'
export TERM="xterm-color"

# History of visited directories in bash
source ~/packages/acd_func.sh

# Set prompt with git (show branch in prompt)
source ~/packages/git-completion.sh
source ~/packages/git-prompt.sh
#export PS1="\h:\W \u\$(__git_ps1 \" (%s)\")\$ "
export PS1="[\u@\h \W]\$(__git_ps1 \" (%s)\")\$ "

#export PROMPT_COMMAND='hpwd=$(history 1); hpwd="${hpwd# *[0-9]*  }"; if [[ ${hpwd%% *} == "cd" ]]; then cwd=$OLDPWD; else cwd=$PWD; fi; hpwd="${hpwd% ### *} ### $cwd"; history -s "$hpwd"'

set -o vi

alias hadoop='/usr/local/hadoop-prd/hadoop/bin/hadoop'
