#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=$PATH:~/packages

# Tell ls to be colourful
eval `dircolors ~/packages/dotfiles/dircolors.256dark`
alias ls='ls --color=auto'
export CLICOLOR=1

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

# History of visited directories in bash
source ~/packages/acd_func.sh

# Set prompt with git (show branch in prompt)
source ~/packages/git-prompt.sh
#export PS1="\h:\W \u\$(__git_ps1 \" (%s)\")\$ "
export PS1="[\u@\h \W]\$(__git_ps1 \" (%s)\")\$ "

# Completions for GIT
source ~/packages/completions/git-completion.sh
# Completions for auto_pack for gogo projects
source ~/packages/completions/auto_pack-completion.sh
# Completions for tmux sessions in tma, tmk (tmux attach, tmux kill, see below)
source ~/packages/completions/tmux-completion.sh

#export PROMPT_COMMAND='hpwd=$(history 1); hpwd="${hpwd# *[0-9]*  }"; if [[ ${hpwd%% *} == "cd" ]]; then cwd=$OLDPWD; else cwd=$PWD; fi; hpwd="${hpwd% ### *} ### $cwd"; history -s "$hpwd"'

set -o vi

alias hadoop='/usr/local/hadoop-prd/hadoop/bin/hadoop'
alias tma='tmux attach-session -t'
alias tmk='tmux kill-session -t'
alias tml='tmux ls'
alias fi='find -iname'
alias fn='find -name'
