execute pathogen#infect()
execute pathogen#helptags()
filetype on
filetype plugin on
filetype plugin indent on
syntax on

" Rebind <Leader> key
let mapleader = ","

"
""" PLUGINS
"
nmap <leader>p :CtrlP<CR>
nmap <leader>b :CtrlPBuffer<CR>
nmap <leader>t :CtrlPTag<CR>
nmap <C-o> :NERDTreeTabsToggle<CR>
map <leader>w :NERDTreeFind<cr>
map <leader>e :BufExplorer<cr>
nnoremap <Leader>fu :CtrlPFunky<Cr>

" Eclim
let g:EclimProjectRefreshFiles = 0

" https://github.com/xolox/vim-session
:let g:session_autosave = 'no'
:let g:session_autoload = 'no'
:let g:session_directory = '~/.vim_sessions'

" Jedi-vim
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = "<leader>d"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>r"
let g:jedi#show_call_signatures = "1"
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 0
" I don't want the docstring window to popup during completion
autocmd FileType python setlocal completeopt-=preview

" Settings for powerline
set laststatus=2   " Always show the statusline
" Settings for ctrlp
let g:ctrlp_user_command = "find %s -type f | egrep '\.(c|h|cpp|hpp|java|proto|py|sh|pl|txt)$'"
let g:ctrlp_by_filename = 0
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_max_height = 30
set wildignore+=*.pyc
set wildignore+=*/coverage/*
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py'
let g:ctrlp_max_files = 0 " no limit
let g:ctrlp_extensions = ['funky']

"
""" MISC
"

" <C-e> and <C-y> scroll the viewport a single line. I like to ratchet this up:
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" bind Ctrl+<movement> keys to move around the windows, instead of using
" Ctrl+w + <movement>
" " Every unnecessary keystroke that can be saved is good for your health :)
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Copy current buffer path relative to root of VIM session to system clipboard
nnoremap <Leader>yp :let @"=expand("%:p")<cr>:echo "Copied file path to clipboard"<cr>
" Copy current filename to system clipboard
nnoremap <Leader>yf :let @"=expand("%:t")<cr>:echo "Copied file name to clipboard"<cr>
" Copy current buffer path without filename to system clipboard
nnoremap <Leader>yd :let @"=expand("%:h")<cr>:echo "Copied file directory to clipboard"<cr>

" change working directory to current opened file
nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

" easier moving between tabs
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>

" Bind nohl
" " Removes highlight of your last search
noremap <C-n> :nohl<CR>

" easier moving of code blocks
" " Try to go into visual mode (v), thenselect several lines of code here and
" " then press ``>`` several times.
vnoremap < <gv " better indentation
vnoremap > >gv " better indentation

" Use <leader>l to toggle display of whitespace
nmap <leader>l :set list!<CR>
" And set some nice chars to do it with
set listchars=tab:>-,trail:·,eol:$

"
" Global
"
set t_ku=OA
set t_kd=OB
set t_kr=OC
set t_kl=OD

"Vim is a little surly, beeping at you at every chance. You can either find a
"way to turn off the bell completely, or more usefully, make the bell visual: 
set visualbell

"When the cursor moves outside the viewport of the current window, the buffer
"scrolls a single line to keep the cursor in view. Setting the option below
"will start the scrolling three lines before the border, keeping more context
"around where you’re working. 
set scrolloff=3

" Swap files and backups are annoying but can save you a lot of trouble.
" Rather than spread them all around your filesystem, isolate them to a single
" directory:
"$ mkdir ~/.vim-tmp  # or whatever
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" Disable vi-compatibility
set nocompatible   
" Explicitly tell Vim that the terminal supports 256 colors
set t_Co=256

set background=dark
" solarized options 
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
let g:solarized_termtrans = 1
colorscheme solarized
"color zenburn

set hidden
set backspace=2 " make backspace work like most other apps
set backspace=indent,eol,start

" Google protocol buffers
autocmd Bufread,BufNewFile *.proto set filetype=javascript
" Python: Better indentation
autocmd BufNewFile,BufRead *.py setlocal nosmartindent

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

" Useful settings
set history=700
set undolevels=700

" Real programmers don't use TABs but spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

" Uncomment the following to have Vim jump to the last position when
" " reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" automatically change window's cwd to file's dir
set autochdir

"
" Showing line numbers and length
" "" set number " show line numbers
" "" set tw=79 " width of document (used by gd)
" "" set nowrap " don't automatically wrap on load
" "" set fo-=t " don't automatically wrap text when typing
" "" set colorcolumn=80
" "" highlight ColorColumn ctermbg=233

