#!/usr/bin/env bash
DEV_TRANSIT="/mnt/disk1/o.ryabukhin/transit"
if [[ $# < 2 ]]; then
	echo "usage: $0 source(git-rep/pack/people-search.tgz) target(aurora15, spider9)"
	exit 1
fi
SOURCE=$1
TARGET=$2
NAME=$(basename $SOURCE)

TMP=$(mktemp -d -t tmp)
scp d:~/$SOURCE $TMP/ && scp $TMP/$NAME dev:$DEV_TRANSIT
rm -r $TMP

ssh -n dev "sudo -u poisk scp $DEV_TRANSIT/$NAME $TARGET:~/; rm $DEV_TRANSIT/$NAME"
