#!/usr/bin/env bash
#rsync -avzr --exclude="*.class" --exclude="*.o" --exclude "*.cpp" --exclude="*.cmake" --exclude="*.make" d:git-rep/tmp/ ~/git-rep/tmp/
rsync -avzr d:git-rep/.classpath ~/git-rep/.classpath
rsync -avzr --cvs-exclude d:git-rep/tmp/contrib/ ~/git-rep/tmp/contrib/
rsync -avzr --cvs-exclude d:git-rep/projects/protogen/python/src.gen/ ~/git-rep/projects/protogen/python/src.gen/
rsync -avzr --cvs-exclude --exclude="*.class" d:git-rep/projects/protogen/java/src.gen/ ~/git-rep/projects/protogen/java/src.gen/
