#!/usr/bin/env bash
ssh d "cd git-rep && make -j16 install_protogen-go.mail.ru && make -j16 install_common-go.mail.ru && make -j16 install_stat-go.mail.ru"

#rsync -avzr --exclude="*.class" --exclude="*.o" --exclude "*.cpp" --exclude="*.cmake" --exclude="*.make" d:git-rep/tmp/ ~/git-rep/tmp/
rsync -avzr d:git-rep/.classpath ~/git-rep/.classpath
rsync -avzr --cvs-exclude d:git-rep/tmp/contrib/ ~/git-rep/tmp/contrib/
rsync -avzr --cvs-exclude d:git-rep/projects/protogen/python/src.gen/ ~/git-rep/projects/protogen/python/src.gen/
rsync -avzr --cvs-exclude --exclude="*.class" d:git-rep/projects/protogen/java/src.gen/ ~/git-rep/projects/protogen/java/src.gen/
rsync -avzr --cvs-exclude --exclude="*.class" d:git-rep/projects/java/stat/src.gen/ ~/git-rep/projects/java/stat/src.gen/ 

rsync -avzr d:git-rep/projects/java/common/src/ru/mail/go/webbase/utils/DomainsLists.java ~/git-rep/projects/java/common/src/ru/mail/go/webbase/utils/DomainsLists.java
