#!/usr/bin/env bash
function sync {
    src=$1
    dst=$2
    opts='-avzr --cvs-exclude --exclude="*.class"'
    echo "Sync from $src to $dst"
    rsync $opts $src $dst 1>/dev/null
}

jars="protogen-go.mail.ru common-go.mail.ru stat-go.mail.ru"

cmd="cd git-rep"
for jar in $jars; do
    cmd+=" && make -j16 install_$jar"
done
ssh d "$cmd"

FROM="d:git-rep"
TO=~/git-rep

cd $TO

for jar in $jars; do
    sync $FROM/bin/$jar.jar ./bin/
done
sync $FROM/tmp/contrib/ ./tmp/contrib/
sync $FROM/projects/protogen/python/src.gen/ ./projects/protogen/python/src.gen/
sync $FROM/projects/protogen/java/src.gen/ ./projects/protogen/java/src.gen/
sync $FROM/projects/java/stat/src.gen/ ./projects/java/stat/src.gen/ 

sync $FROM/projects/java/common/src/ru/mail/go/webbase/utils/DomainsLists.java ./projects/java/common/src/ru/mail/go/webbase/utils/DomainsLists.java
sync $FROM/.classpath ./.classpath

sed -i '/contrib\/hadoop-0.20.2-cdh3u4m20\/lib\/commons-lang-2.4.jar/d' .classpath

cd -
